export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

//USER ACTIONS

export const CHECK_LOGGED_IN_STATUS = 'CHECK_LOGGED_IN_STATUS';
export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS'
export const PENDING_USER_LOGIN = 'PENDING_USER_LOGIN'
export const ERROR_LOGGING_IN = 'ERROR_LOGGING_IN'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTERING_USER = 'REGISTERING_USER'
export const ERROR_REGISTERING_USER = 'ERROR_REGISTERING_USER'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const SUCCESSFUL_GET_USER = 'SUCCESSFUL_GET_USER'
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'



//full screen dialog

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';



//alerts

export const UPDATE_ALERT = 'OPEN_ALERT';
export const CLOSE_ALERT = 'CLOSE_ALERT';


//recipes

export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

//facets

export const ADD_FACET = 'ADD_FACET'
export const REMOVE_FACET = 'REMOVE_FACET'
export const UPDATE_AVAILABLE_FACETS = 'UPDATE_AVAILABLE_FACETS';
export const UPDATE_FACET_FILTERS = 'UPDATE_FACET_FILTERS'




